# GENERAL PARAMS
EXPERIMENT_NAME: null # Overrides automatic experiment naming 
SEED: 2
DATASET_DIR: '/home/franek/SurgLatentGraph/data/mmdet_datasets/endoscapes'
# DATA PARAMS
DATA:
  IMG_SIZE: 384
# SWINCVS MODEL PARAMS
MODEL:
  LSTM: True
  LSTM_PARAMS:
    NUM_LAYERS: 2
    HIDDEN_SIZE: 256
  E2E: True # Decides if backbone is frozen in training
  MULTICLASSIFIER: True # Classifier WILL NOT be implemented if E2E=False
  INFERENCE: True
  INFERENCE_WEIGHTS: 'SwinV2LSTM_e2e_raw_mc_V3_sd5_bestMAP.pt'
# TRAINING PARAMS
TRAIN:
  EPOCHS: 2
  LIMIT_DATA_FRACTION: 50 # For testing, regular set to 1
  TRANSFORMS:
    ENDOSCAPES_MEAN: [0.485, 0.456, 0.406]
    ENDOSCAPES_STD: [0.229, 0.224, 0.225]
    CENTER_CROP: 480
  BATCH_SIZE: 1
  OPTIMIZER:
    NAME: 'adamw'
    EPS: 1.0e-08
    BETAS: [0.9, 0.999]
    WEIGHT_DECAY: 0.02
    ENCODER_LR: 0.00001
    CLASSIFIER_LR: 0.001
  CLASS_WEIGHTS: [3.19852941, 4.46153846, 2.79518072]
  WARMUP_EPOCHS: 4
  WARMUP_LR: 0.001
  BASE_LR: 0.001
  MIN_LR: 0.0000001
  MULTICLASSIFIER_ALPHA: 0.8
  SAVE_WEIGHTS: True
  CHECKPOINT_PATH: '/home/franek/SwinCVS/weights'
  LR_SCHEDULER:
    NAME: 'cosine'
    WARMUP_PREFIX: False
  CLIP_GRAD: 5
  ACCUMULATION_STEPS: 1
# SWINV2 BACKBONE PARAMS
BACKBONE:
  PRETRAINED: 'swinv2_base_patch4_window12to24_192to384_22kto1k_ft.pth' #'Swin_backbone_no_augm_sd4_bestMAP.pt'
  DROP_PATH_RATE: 0.2
  DROP_RATE: 0.0
  NUM_CLASSES: 1000
  SWINV2:
    PATCH_SIZE: 4
    IN_CHANS: 3
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 24
    PRETRAINED_WINDOW_SIZES: [ 12, 12, 12, 6 ]
    MLP_RATIO: 4
    QKV_BIAS: True
    APE: False
    PATCH_NORM: True
  USE_CHECKPOINT: False
  
