EXPERIMENT_NAME: 'SwinCVS_inference'
SEED: 2
DATA:
  IMG_SIZE: 384
BACKBONE:
  PRETRAINED: 'weights/swinv2_base_patch4_window12to24_192to384_22kto1k_ft.pth'
  DROP_PATH_RATE: 0.2
  DROP_RATE: 0.0
  NUM_CLASSES: 1000
  SWINV2:
    PATCH_SIZE: 4
    IN_CHANS: 3
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 24
    PRETRAINED_WINDOW_SIZES: [ 12, 12, 12, 6 ]
    MLP_RATIO: 4
    QKV_BIAS: True
    APE: False
    PATCH_NORM: True
  USE_CHECKPOINT: False
MODEL:
  LSTM: True
  LSTM_PARAMS:
    NUM_LAYERS: 2
    HIDDEN_SIZE: 256
  E2E: True
  MULTICLASSIFIER: True
  INFERENCE: True
  ENDOSCAPES_PRETRAINED: null
TRAIN:
  OPTIMIZER:
    NAME: 'adamw'
    EPS: 1.0e-08
    BETAS: (0.9, 0.999)
    WEIGHT_DECAY: 0.02
    ENCODER_LR: 1e-5
    CLASSIFIER_LR: 1e-3
  EPOCHS: 1
  WARMUP_EPOCHS: 4
  WARMUP_LR: 1e-3
  BASE_LR: 1e-3
  MIN_LR: 1e-7
  LR_SCHEDULER:
    NAME: 'cosine'
    WARMUP_PREFIX: False
  CLIP_GRAD: 5
  ACCUMULATION_STEPS: 1
  
